<h1 class="text-center">Atualizar dados do Policial</h1>
<br />
<form id="<?php echo $this->form->getAttrib('id') ?>" class="form-horizontal"
      name="<?php echo $this->form->getAttrib('name') ?>"
      action="<?php echo $this->form->getAction() ?>"
      method="<?php echo $this->form->getMethod() ?>">
    <?php echo $this->form->id_policial ?>
    <div class="row-fluid">
        <div class="control-group span4">
            <label class="control-label" for="matricula"><?php echo $this->form->matricula->getLabel() ?></label>
            <?php echo $this->form->matricula ?>
        </div>
        <div class="control-group span8">
            <label class="control-label" for="nome"><?php echo $this->form->nome->getLabel() ?></label>
            <?php echo $this->form->nome ?>
        </div>
    </div>
    <div class="row-fluid">    
        <div class="control-group span4">
            <label class="control-label" for="patente"><?php echo $this->form->patente->getLabel() ?></label>
            <?php echo $this->form->patente ?>
        </div>
        <div class="control-group span8">
            <label class="control-label" for="nome_guerra"><?php echo $this->form->nome_guerra->getLabel() ?></label>
            <?php echo $this->form->nome_guerra ?>
        </div>
    </div>
    <div class="row-fluid">
        <?php echo $this->form->submit ?>
    </div>
</form>