<form id="<?php echo $this->form->getAttrib('id') ?>" class="form-horizontal" name="<?php echo $this->form->getAttrib('name') ?>" action="<?php echo $this->form->getAction() ?>" method="<?php echo $this->form->getMethod() ?>">
    <?php echo $this->form->id_ocorrencia ?>
    <div class="row-fluid">
        <div class="control-group span3">
            <label class="control-label" for="data"><?php echo $this->form->data->getLabel() ?></label>
            <?php echo $this->form->data ?>
        </div>
        <div class="control-group span3">
            <label class="control-label" for="prefixo"><?php echo $this->form->prefixo->getLabel() ?></label>
            <?php echo $this->form->prefixo ?>
        </div>
        <div class="control-group span3">
            <label class="control-label" for="ciade"><?php echo $this->form->ciade->getLabel() ?></label>
            <?php echo $this->form->ciade ?>
        </div>
        <div class="control-group span3">
            <label class="control-label" for="dp"><?php echo $this->form->dp->getLabel() ?></label>
            <?php echo $this->form->dp ?>
        </div>
    </div>
    <div class="row-fluid">
        <div class="control-group span3">
            <label class="control-label" for="bo"><?php echo $this->form->bo->getLabel() ?></label>
            <?php echo $this->form->bo ?>
        </div>
        <div class="control-group span3">
            <label class="control-label" for="flagrante"><?php echo $this->form->flagrante->getLabel() ?></label>
            <?php echo $this->form->flagrante ?>
        </div>
        <div class="control-group span3">
            <label class="control-label" for="tc"><?php echo $this->form->tc->getLabel() ?></label>
            <?php echo $this->form->tc ?>
        </div>
        <div class="control-group span3">
            <label class="control-label" for="paai"><?php echo $this->form->paai->getLabel() ?></label>
            <?php echo $this->form->paai ?>
        </div>
    </div>
    <hr />
    <div class="row-fluid">
        <div class="control-group span8">
            <label class="control-label" for="natureza">Natureza:</label>
            <?php echo $this->form->natureza ?>
        </div>
        <div class="control-group span4">
            <label class="control-label" for="codigo">Codigo:</label>
            <input type="text" name="codigo" id="codigo" class="input-large" placeholder="Codigo">
        </div>
    </div>
    <?php echo $this->form->id_endereco ?>
    <div class="row-fluid">
        <div class="control-group span4">
            <label class="control-label" for="subarea"><?php echo $this->form->sub_area->getLabel() ?></label>
            <?php echo $this->form->sub_area ?>
        </div>
        <div class="control-group span4">
            <label class="control-label" for="setor"><?php echo $this->form->setor->getLabel() ?></label>
            <?php echo $this->form->setor ?>
        </div>
        <div class="control-group span4">
            <label class="control-label" for="endereco"><?php echo $this->form->complemento->getLabel() ?></label>
            <?php echo $this->form->complemento ?>
        </div>
    </div>
    <hr />
    <div class="row-fluid">
        <div class="control-group span2">
            <label class="control-label" for="acionamento"><?php echo $this->form->irradiacao->getLabel() ?></label>
            <?php echo $this->form->irradiacao ?>
        </div>
        <div class="control-group span2">
            <label class="control-label" for="chegada_local"><?php echo $this->form->chegada_local->getLabel() ?></label>
            <?php echo $this->form->chegada_local ?>
        </div>
        <div class="control-group span2">
            <label class="control-label" for="termino_local"><?php echo $this->form->termino_local->getLabel() ?></label>
            <?php echo $this->form->termino_local ?>
        </div>
        <div class="control-group span2">
            <label class="control-label" for="chegada_dp"><?php echo $this->form->chegada_dp->getLabel() ?></label>
            <?php echo $this->form->chegada_dp ?>
        </div>
        <div class="control-group span2">
            <label class="control-label" for="termino_dp"><?php echo $this->form->termino_dp->getLabel() ?></label>
            <?php echo $this->form->termino_dp ?>
        </div>
    </div>
    <hr />
    <div class="row-fluid">
        <div class="control-group span3">
            <input type="radio" name="situacao1" value="D">Detido
            <input type="radio" name="situacao1" value="P">Preso
            <input type="radio" name="situacao1" value="A">Apreendido
            <br />
            <input type="radio" name="sexo1" value="M">Masculino
            <input type="radio" name="sexo1" value="F">Feminino
            <div class="control-group">
                <label class="control-label" for="inputIdade1">Idade:</label>
                <input type="text" name="idade1" class="input-mini" placeholder="Idade">
            </div>
        </div>
        <div class="control-group span3">
            <input type="radio" name="situacao2" value="D">Detido
            <input type="radio" name="situacao2" value="P">Preso
            <input type="radio" name="situacao2" value="A">Apreendido
            <br />
            <input type="radio" name="sexo2" value="M">Masculino
            <input type="radio" name="sexo2" value="F">Feminino
            <div class="control-group">
                <label class="control-label" for="inputIdade1">Idade:</label>
                <input type="text" name="idade2" class="input-mini" placeholder="Idade">
            </div>
        </div>
        <div class="control-group span3">
            <input type="radio" name="situacao3" value="D">Detido
            <input type="radio" name="situacao3" value="P">Preso
            <input type="radio" name="situacao3" value="A">Apreendido
            <br />
            <input type="radio" name="sexo3" value="M">Masculino
            <input type="radio" name="sexo3" value="F">Feminino
            <div class="control-group">
                <label class="control-label" for="inputIdade3">Idade:</label>
                <input type="text" name="idade3" class="input-mini" placeholder="Idade">
            </div>
        </div>
        <div class="control-group span3">
            <input type="radio" name="situacao4" value="D">Detido
            <input type="radio" name="situacao4" value="P">Preso
            <input type="radio" name="situacao4" value="A">Apreendido
            <br />
            <input type="radio" name="sexo4" value="M">Masculino
            <input type="radio" name="sexo4" value="F">Feminino
            <div class="control-group">
                <label class="control-label" for="inputIdade4">Idade:</label>
                <input type="text" name="idade4" class="input-mini" placeholder="Idade">
            </div>
        </div>
    </div>
    <hr />
    <div class="row-fluid">
        <div class="control-group span4">
            <label class="control-label" for="comandante">CMT Guarnicao:</label>
            <input type="text" name="comandante" id="comandante" class="input-medium" placeholder="Comandante">
        </div>
        <div class="control-group span2">
            <label class="control-label" for="matricula_comandante">Matricula:</label>
            <input type="text" name="matricula_comandante" id="matricula_comandante" class="input-mini" placeholder="Matricula">
        </div>
        <div class="control-group span4">
            <label class="control-label" for="policial1">Policial 01:</label>
            <input type="text" name="policial1" id="policial1" class="input-medium" placeholder="Policial 01">
        </div>
        <div class="control-group span2">
            <label class="control-label" for="matricula1">Matricula:</label>
            <input type="text" name="matricula1" id="matricula1" class="input-mini" placeholder="Matricula">
        </div>
    </div>
    <div class="row-fluid">
        <div class="control-group span4">
            <label class="control-label" for="policial2">Policial 02:</label>
            <input type="text" name="policial2" id="policial2" class="input-medium" placeholder="Policial 02">
        </div>
        <div class="control-group span2">
            <label class="control-label" for="matricula2">Matricula:</label>
            <input type="text" name="matricula2" id="matricula2" class="input-mini" placeholder="Matricula">
        </div>
        <div class="control-group span4">
            <label class="control-label" for="policial3">Policial 03:</label>
            <input type="text" name="policial3" id="policial3" class="input-medium" placeholder="Policial 03">
        </div>
        <div class="control-group span2">
            <label class="control-label" for="matricula3">Matricula:</label>
            <input type="text" name="matricula3" id="matricula3" class="input-mini" placeholder="Matricula">
        </div>
    </div>
    <hr />
    <div class="row-fluid">
        <div class="span12">
            Observacoes:<br />
            <?php echo $this->form->observacao ?>
        </div>
    </div>
    <?php echo $this->form->submit ?>
</form>